name: "Run tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Format files
      run: |
        pip install black
        black .
    - name: Sort imports
      run: |
        pip install isort
        isort .
    - name: Type checking
      run: |
        pip install mypy
        mypy .

